### ISSUE TITLE
support koa v1? / Multipart: Boundary not found

### ISSUE THREAD

**Issue by mezod** [hirako2000/koa-router-multer#2]
I see that the example in the docs is the example of koa-router for koa 2.x, so I wonder, does this middleware also work for koa 1.x?

I have tried it and I'm getting 'Error: Multipart: Boundary not found'. So I'm wondering if it's just that it doesn't support koa 1.x or something else. Thanks

**Comment by mezod** [comment]
Yep, it does.

For anyone stumbling upon this issue, my problem was that I was setting the content-type header manually in Postman and you don't have to.

**Comment by hirako2000** [comment]
I had not tested with koa1,  so I wasn't guaranting things would play well with it. 
Good to know it works and that it addresses your Multipart support. 

Thanks
